---
title: '@jumping_uk Twitter Analysis'
author: "David Saipe"
date: 'July 26, 2022'
output: 
  word_document:
    toc: TRUE
    toc_depth: 2
    fig_width: 6.5
    fig_height: 4.5
editor_options: 
  markdown: 
    wrap: 72
date: '2022-07-06'
output: html_document
fig_width: 6
fig_height: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(rtweet)
library(dplyr)
library(ggplot2)
library(stringr)
library(lubridate)
library(patchwork)
library(tidyr)
library(magrittr)
library(tidytext)
library(ggwordcloud)
library(plotrix)
```

------------------------------------------------------------------------

# Introduction

The @jumping_uk account has been active since March 2016 and has almost
8000 followers. The account is currently posting very regularly (most
weekdays). This year, the account is currently on track to posting its
most tweets in one year. 

```{r jr timeline, echo = FALSE, }
jr_timeline = read.csv("Data/jr_timeline.csv")

jr_timeline %<>%
  filter(is_retweet == FALSE) %>%
  select(status_id, created_at, text, favorite_count, retweet_count, 
         mentions_screen_name, urls_url, hashtags, media_type) %>%
  mutate(hour_posted = hour(created_at), 
         interactions = retweet_count + favorite_count,
         year = year(created_at))
jr_timeline$status_id = gsub("x", "", as.character(jr_timeline$status_id))

ggplot(jr_timeline, aes(year)) +
  geom_point(stat = "count") +
  geom_line(stat = "count") +
  xlim(2016,2021) +
  xlim(2017,2021) +
  theme_classic() +
  xlab("Year") +
  ylab("Number of Tweets")
```

This report will look into several factors that affect levels of
engagement on Twitter - including what day and time a tweet is posted,
the use of hashtags and the use of media. I have used the RTweet package
to get the data for this analysis, and have primarily been looking at
data from the @jumping_uk timeline, as well as general tweets that use
'#rstats'. 

```{r #rstats, include = FALSE}
rstats = read.csv("Data/rstats_hashtag.csv")

rstats %<>%
  select(screen_name, created_at, favorite_count, retweet_count, hashtags, 
         media_type, mentions_screen_name, urls_url) %>%
  mutate(hashtag_num = str_count(hashtags, "\\w+"),
         interactions = retweet_count + favorite_count,
         hour_posted = hour(created_at))
```

\newpage

# Time Posted

## Day of the Week

There is mixed opinion about whether tweets posted on the weekend
receive as much interaction as those posted during in the week. The best
day to post a tweet usually depends on the type of content that is being
posted, and the account it is being posted from. For example, one
article suggests that the best time to post about consumer goods is on
the weekend, whereas the best time to post for technical business is
during the week. @jumping_uk's timeline corroborates with this idea as
tweets that are posted on Saturdays and Sundays usually receive less
retweets and likes, compared to tweets posted during the week.

## Best day of the week to post

It is widely agreed upon that tweets posted on the weekend will receive less engagement from the users audience. @jumping_uk's timeline corroborates with this. Tweets posted on Saturdays and Sundays have generally received significantly less retweets and likes. 

```{r day of the week, echo = FALSE}
by_weekday = jr_timeline %>%
  mutate(day = lubridate::wday(created_at, label = TRUE, abbr = TRUE, week_start = getOption("lubridate.week.start", 1)))

ggplot(by_weekday, aes(day, interactions)) + 
  geom_boxplot(fill = "#d95f02") +
  labs(caption = "Taken from @jumping_uk timeline from 2016 to 2022") +
  xlab("Day") +
  ylab("Interactions") +
  scale_y_log10() +
  theme_classic()
```

In recent months the account has only been posting on weekdays, and this seems to be the right thing to be doing. More important tweets could start being posted on Mondays and Tuesdays, although there is little evidence to suggest that this would be beneficial.  

\newpage

## Hour of the Day

From looking at the @jumping_uk timeline, tweets posted between 8-11am have generally received the highest number of interactions. There are however spikes in engagement from 2pm onwards. 

```{r time posted, echo = FALSE}
avg_interactions = jr_timeline %>%
  filter(interactions < 100) %>%
  group_by(hour_posted) %>%
  summarise(mean = mean(interactions),
            se = std.error(interactions))

avg_interactions = avg_interactions[-c(1,2),]

ggplot(avg_interactions, aes(hour_posted, mean)) +
  geom_bar(fill = "#1b9e77", color = "black", stat = "identity") +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se),
                width = .2, position = position_dodge(.9)) +
  labs(caption = "Taken from @jumping_uk timeline from 2016 to 2022") +
  xlim(6,24) +
  xlab("Hour Posted") + 
  ylab("Interactions") +
  theme_classic()
```

Examining the locations of people retweeting @jumping_uk tweets, there
is a higher proportion of retweeters in the afternoon peak that are from
America, with a lower proportion being from Asia and Africa. The
proportion of retweeters from the UK is similar during both peaks.

```{r retweeter locations, echo = FALSE}
morning_retweeters = read.csv("Data/morning_retweeters.csv")
morning_retweeters = morning_retweeters[-c(61:93),] %>%
  group_by(location) %>%
  mutate(count = n())

afternoon_retweeters = read.csv("Data/afternoon_retweeters.csv")
afternoon_retweeters = afternoon_retweeters[-c(104:147),] %>%
  group_by(location) %>%
  mutate(count = n())

am = ggplot(morning_retweeters, 
       aes(x = "", y = count, fill = location)) +
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start = 0) +
  scale_fill_brewer(palette = "Dark2", name = "Continent") +
  labs(subtitle = "Morning peak") +
  theme_void() +
  theme(plot.subtitle = element_text(hjust = 0.5),
        legend.position = "none")

pm = ggplot(afternoon_retweeters, 
       aes(x = "", y = count, fill = location)) +
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start = 0) +
  scale_fill_brewer(palette = "Dark2", name = "Continent") +
  labs(subtitle = "Afternoon peak") +
  theme_void() +
  theme(plot.subtitle = element_text(hjust = 0.5)) 

am +
  labs(title = "Locations of @jumping_uk retweeters") + 
  pm
```

The difference in the locations of morning retweeters and afternoon
retweeters means that tweets can be targeted to specific audiences
through the time that they are posted. For example, tweets about the
ongoing RStudio Conference may receive more interaction when tweeted
between 2pm-4pm, as the conference is being held in Washington.

It should also 
be taken into account that around 75% of @rstatstweet followers are from America, 
so tweets containing #rstats may receive more engagement in the afternoon.

```{r rstats follower locations, echo = FALSE}
rstats_followers = read.csv("Data/rstats_followers2.csv")
rstats_followers = rstats_followers[1:216,]
rstats_followers %<>%
  select(location)
rstats_followers %<>%
  group_by(location) %>%
  mutate(count = n())
ggplot(rstats_followers, 
       aes(x = "", y = count, fill = location)) +
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start = 0) +
  scale_fill_brewer(palette = "Dark2", name = "Continent") +
  labs(title = "Locations of @rstatstweet followers",
       caption = "Based off a sample of 500 followers") +
  theme_void()
```

Despite this, it is important to tweet during both peaks of the day.
Tweets come and go off the timeline very quickly so it's important to
post and multiple times of the day to ensure it reaches as many
followers as possible.

\newpage

# Images

Images do affect levels of engagement positively. The figure below shows
the average levels of interaction for tweets with no media and tweets
that include a photo, taken from both the #rstats timeline and the
@jumping_uk timeline.

```{r images, echo = FALSE}
rstats = rstats[-c(29, 3913),]

avg_interactions = jr_timeline %>%
  group_by(media_type) %>%
  summarise(jr_interactions = mean(interactions))
avg_interactions %<>%
  mutate(rstats %>%
           group_by(media_type) %>%
           summarise(rstats_interactions = mean(interactions)))

avg_interactions$media_type[1] = c("None")
avg_interactions$media_type[2] = c("Photo")

avg_interactions %>%
  pivot_longer(cols = c("jr_interactions",
                      "rstats_interactions"),
             names_to = "interactions",
             values_to = "count") %>%
  ggplot(aes(x = media_type, y = count, 
             fill = interactions)) +
  geom_col(position = "dodge") +
  xlab("Media") +
  ylab("Average Interactions") + 
  scale_fill_brewer(palette = "Dark2", 
                    name = "Source",
                    labels = c("@jumping_uk", "#rstats")) +
  theme_classic()
```

Including images is a good start to increasing engagement. Having
consistent branding is also important for keeping the page professional
looking. Images can also be used to include information can can't be
compressed into 280 characters.

\newpage

# Hashtags

There are multiple bots on twitter that retweet tweets containing #rstats (@rstatstweet and @rstats4ds are the two main ones). This
hashtag should always be included in @jumping_uk tweets. Below are the
top 30 most commonly used hashtags alongside #rstats, taken from the 100
most popular tweets containing #rstats (07/07 - 14/07).

```{r hashtags wordcloud, echo = FALSE}
rstats_top = rstats %>%
  filter(interactions >= 225)
rstats_count = unnest_tokens(tbl = rstats_top,
                            output = word,
                            input = hashtags)
rstats_count = count(rstats_count, word, sort = TRUE) 

rstats_count %>%
  slice_max(n, n = 30) %>%
  ggplot(aes(label = word, size = n)) +
  geom_text_wordcloud() +
  scale_size_area(max_size = 10) +
  labs(caption = "Taken from the top 100 most popular tweets containing #rstats from 07/07 - 14/07") +
  theme_void()
```

Other than #rstats, @jumping_uk uses #datascience, #python, #tidyverse
and #shiny most often. The bar chart below shows the impact of these
four hashtags when used alongside #rstats. They all improve engagement,
so should continue to be used when relevant.

```{r jr hashtags, echo = FALSE}
jr_hashtags = tibble(
  hashtags = c("shiny", "datascience", "python",
               "tidyverse"),
  interactions_used = c(13.6, 10.8, 10.6, 11.4),
  interactions_not_used = c(9.2, 9.3, 9.4, 9.5)
)

jr_hashtags %>% 
  pivot_longer(
    cols = c("interactions_used", "interactions_not_used"),
    names_to = c("interactions"),
    values_to = c("count")
  ) %>%
  ggplot(aes(hashtags, count, fill = interactions)) +
  geom_col(position = "dodge") + 
  scale_fill_brewer(palette = "Dark2", 
                    name = "Hashtag Used",
                    labels = c("No", "Yes")) +
  labs(title = "Impact of hashtags used alongside #rstats",
       caption = "Taken from @jumping_uk timeline from 2016 to 2022") +
  xlab("Hashtag") +
  ylab("Average Interactions") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 30,
                                   size = 6,
                                   vjust = 0.7),
        plot.title = element_text(hjust = 0.3))
```

@jumping_uk doesn't use #machinelearning and #bigdata as often; these
are two hashtags that are often found in the most popular tweets on the #rstats timeline. The figure below shows that these have a significant
impact on engagement on #rstats tweets, and so they could be used more
often in the future.

```{r rstats hashtags, echo = FALSE}
rstats_hashtags = tibble(
  hashtags = c("stats", "datascience", "python", 
               "machinelearning", "bigdata"),
  used = c(80.71, 35.73, 37.28, 36.1, 40.3),
  not_used = c(29.45, 24.62, 24, 25.14, 22.35)
)
rstats_hashtags %>%
  pivot_longer(cols = c("used", "not_used"),
               names_to = "interactions",
               values_to = "count") %>%
  ggplot(aes(hashtags, count, fill = interactions)) +
           geom_col(position = "dodge") +
  scale_fill_brewer(palette = "Dark2", 
                    name = "Hashtag Used",
                    labels = c("No", "Yes")) +
  labs(title = "Impact of hashtags used alongside #rstats",
       caption = "Taken from #rstats tweets from 07/07 - 14/07") +
  xlab("Hashtag") +
  ylab("Average Interactions") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 30,
                                   size = 6,
                                   vjust = 0.7),
        plot.title = element_text(hjust = 0.5))

```

There are also hashtag trends such as #100daysofcode and #tidytuesdays
which could be good ways to appear more on the RStats community
timeline. There are two accounts that retweet all tweets with #100daysofcode.

It is also important not to include too many hashtags, as this can
appear to be 'spammy', causing users to scroll straight past without
reading the content of the tweet. A good way to use hashtags can be by
including it in the main bulk of the tweet where the word in question
would be appearing anyway.

# Conclusion

The factors analysed in this report have an effect on the levels of
engagement with @jumping_uk tweets to varying extents.

There are indeed optimum times of the day to post on twitter. However,
because of the difference in audience during the morning and afternoon,
the best thing would be to post twice a day. Tweets can be tailored this
way to match the receiving audience, with afternoon tweets being
targeted towards American users, and morning tweets being targeted
towards users in Asia and Africa.

It was already apparent that images were increasing the numbers of likes
and retweets on @jumping_uk posts, and this analysis has helped confirm
that. It is always appropriate to include images in tweets, and when a
URL is included within the body of a tweet, it is important to ensure
that a summary card appears when the tweet is posted.

@jumping_uk are already using some of the main hashtags used alongside #rstats in popular tweets. There are some hashtags which could be used
more, such as #bigdata, #machinelearning, #programming, and #datascientist. 
It would also be worth following some of the #rstats
bots, as they don't always retweet #rstats tweets.

------------------------------------------------------------------------
